<a href="https://colab.research.google.com/github/Upasna22/AdapterViews/blob/master/POC-MCC-model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
train_df = pd.read_csv('POC-MCCdata.csv')

In [59]:
train_df.head()

TableTypeId IndustryTemplateCode  ... FileSource CountryId
0            1                    N  ...          2       CAN
1            1                    N  ...          2       CAN
2            1                    N  ...          2       CAN
3            1                    N  ...          2       CAN
4            1                    N  ...          2       CAN

[5 rows x 15 columns]

In [60]:
train_df['MsId'].describe()

count         237911
unique           240
top       V2ID000003
freq           47051
Name: MsId, dtype: object

Label encoding


In [61]:
#Split data into X and y
X = train_df.copy()
#y = train_df['MsId']
#X = train_df.drop(['MsId'], axis=1)
X.head()


TableTypeId IndustryTemplateCode  ... FileSource CountryId
0            1                    N  ...          2       CAN
1            1                    N  ...          2       CAN
2            1                    N  ...          2       CAN
3            1                    N  ...          2       CAN
4            1                    N  ...          2       CAN

[5 rows x 15 columns]

In [0]:
from sklearn.preprocessing import LabelEncoder
def LabelEncoding(X):
  labelEncodedTrain = pd.DataFrame()
  LE = LabelEncoder()
  for col in X.columns:
    if(X[col].dtype == 'object'):
      labelEncodedTrain[col] = LE.fit_transform(X[col])
    else:
      labelEncodedTrain[col] = X[col]
  print('Label Encoded Train looks like \n{}'.format(labelEncodedTrain.head(15)))
  print(labelEncodedTrain.shape)

In [62]:
#drop unwanted columns like Dates
X = X.drop(['EffectiveDate', 'CreateDate', 'UpdateDate'], axis=1)
X.head()

TableTypeId IndustryTemplateCode    FileId  ... AMItemId FileSource CountryId
0            1                    N  31953224  ...  6643918          2       CAN
1            1                    N  31953224  ...  6643919          2       CAN
2            1                    N  31953224  ...  6643920          2       CAN
3            1                    N  31953224  ...  6643921          2       CAN
4            1                    N  31953224  ...  6643922          2       CAN

[5 rows x 12 columns]

In [40]:
#target variable
y.head()


0    V2ID000003
1    V2ID000003
2    IFBS200660
3    IFBS100688
4    IFBS002631
Name: MsId, dtype: object

In [63]:
category_train_df = X.select_dtypes(include=['object']).copy()
print("cateegorical data is")
category_train_df.head()

cateegorical data is


IndustryTemplateCode   CompanyId  ...   IndustryName CountryId
0                    N  0C0000099P  ...  Oil & Gas E&P       CAN
1                    N  0C0000099P  ...  Oil & Gas E&P       CAN
2                    N  0C0000099P  ...  Oil & Gas E&P       CAN
3                    N  0C0000099P  ...  Oil & Gas E&P       CAN
4                    N  0C0000099P  ...  Oil & Gas E&P       CAN

[5 rows x 8 columns]

In [78]:
total_missing_values = X.isnull().sum().sort_values(ascending=False)
percentage_missing_values = (X.isnull().sum() / X.isnull().count()).sort_values(ascending =False)
missing_data = pd.concat([total_missing_values, percentage_missing_values], keys = ['Total', 'Percentage'], axis=1)
missing_data.head(20)


Total  Percentage
CountryId                 0         0.0
FileSource                0         0.0
AMItemId                  0         0.0
IndustryName              0         0.0
SectorName                0         0.0
Company ReportedName      0         0.0
MS ReportedName           0         0.0
MsId                      0         0.0
CompanyId                 0         0.0
FileId                    0         0.0
IndustryTemplateCode      0         0.0
TableTypeId               0         0.0

In [0]:
#One Hot Encoding : Takes a categorical value and converts it to a binary vector of size n(no:of values in category)

from sklearn.preprocessing import OneHotEncoder

def oneHotEncoding(X):
  oneHotencoder = OneHotEncoder(handle_unknown='ignore')
  oneHotencoder.fit(X)
  oneHotEncodedTrain = oneHotencoder.transform(X)
  return oneHotEncodedTrain
  print('One Hot Encoded train data looks like:\n {}'.format(oneHotEncodedTrain))
  print('One Hot Endcoded data has {} rows and {} columns'.format(oneHotEncodedTrain.shape[0], oneHotEncodedTrain.shape[1]))

Total  Percentage
CountryId                 0         0.0
FileSource                0         0.0
AMItemId                  0         0.0
IndustryName              0         0.0
SectorName                0         0.0
Company ReportedName      0         0.0
MS ReportedName           0         0.0
MsId                      0         0.0
CompanyId                 0         0.0
FileId                    0         0.0
IndustryTemplateCode      0         0.0
TableTypeId               0         0.0

In [0]:
columnsToBeDropped = missing_data[missing_data['Total'] > 1].index

In [66]:
print(columnsToBeDropped)

Index(['MS ReportedName', 'Company ReportedName', 'MsId'], dtype='object')


In [0]:
nullObservation = X.loc[X['MS ReportedName'].isnull()].index
nullObservation2 = X.loc[X['Company ReportedName'].isnull()].index
nullObservation3 = X.loc[X['MsId'].isnull()].index

In [76]:
print(nullObservation)
print(nullObservation2)
print(nullObservation3)

Int64Index([], dtype='int64')
Int64Index([113762, 148986, 195584, 204162, 212199, 223478, 233804, 234491], dtype='int64')
Int64Index([21375, 32555, 43230, 61293, 95712, 120873, 127588, 169070, 183198], dtype='int64')


In [0]:

for obsv2 in nullObservation2:
  X = X.drop(obsv2)

for obsv3 in nullObservation3:
  X = X.drop(obsv3)
  

In [79]:
#split data into X and target y
train_data = X.copy()
y = X['MsId']
Xtrain = X.drop(['MsId'], axis=1)
print(Xtrain.shape)
print(y.shape)

(237878, 11)
(237878,)


In [80]:
Xtrain.head()

TableTypeId IndustryTemplateCode    FileId  ... AMItemId FileSource CountryId
0            1                    N  31953224  ...  6643918          2       CAN
1            1                    N  31953224  ...  6643919          2       CAN
2            1                    N  31953224  ...  6643920          2       CAN
3            1                    N  31953224  ...  6643921          2       CAN
4            1                    N  31953224  ...  6643922          2       CAN

[5 rows x 11 columns]

In [89]:
from sklearn.preprocessing import LabelEncoder
cat_labeled = Xtrain.copy()
#cat_labeled = cat_labeled.astype('category').dtypes
LE = LabelEncoder()
cat_labeled.head()
#print(cat_labeled.dtypes)
cat_labeled['IndustryTemplateCode'] =  LE.fit_transform(Xtrain['IndustryTemplateCode'])
cat_labeled['CompanyId'] =  LE.fit_transform(Xtrain['CompanyId'])
cat_labeled['MS ReportedName'] =  LE.fit_transform(Xtrain['MS ReportedName'])
cat_labeled['Company ReportedName'] =  LE.fit_transform(Xtrain['Company ReportedName'])
cat_labeled['SectorName'] =  LE.fit_transform(Xtrain['SectorName'])
cat_labeled['IndustryName'] =  LE.fit_transform(Xtrain['IndustryName'])
cat_labeled['CountryId'] =  LE.fit_transform(Xtrain['CountryId'])
cat_labeled.head()

TableTypeId  IndustryTemplateCode    FileId  ...  AMItemId  FileSource  CountryId
0            1                     1  31953224  ...   6643918           2          0
1            1                     1  31953224  ...   6643919           2          0
2            1                     1  31953224  ...   6643920           2          0
3            1                     1  31953224  ...   6643921           2          0
4            1                     1  31953224  ...   6643922           2          0

[5 rows x 11 columns]

In [101]:
cat_labeled_y = LE.fit_transform(y)
print(cat_labeled_y.shape)
print(cat_labeled_y[0:30000])

(237878,)
[239 239 234 ...  60 239 239]


In [105]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
#split data into train and test sets

X_train, X_test, y_train, y_test = train_test_split(cat_labeled[0:30000], cat_labeled_y[0:30000], test_size=0.33)

#fit model 
model = XGBClassifier()
model.fit(X_train, y_train)

print(model)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)


In [0]:
#make predictions for test data
y_pred = model.predict(X_test)

In [108]:
from sklearn.metrics import accuracy_score, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)
print("Accurancy: %.2f%%" %(accuracy * 100.0))

confusionMatrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix: {}", confusionMatrix)

Accurancy: 75.02%
Confusion Matrix: {} [[ 228    0    0 ...    0    0    0]
 [   5  251    0 ...    0    0    2]
 [   0    0    1 ...    0    0    0]
 ...
 [   0    0    0 ...    5    0    0]
 [   0    0    0 ...    0   27    2]
 [   0    5    0 ...    0    2 1828]]
